"""Model update

Revision ID: aaf035d55e3f
Revises: 
Create Date: 2024-04-25 22:41:19.528370

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from app.model.event import EventTypeEnum


# revision identifiers, used by Alembic.
revision = 'aaf035d55e3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    EventTypeEnum.create(op.get_bind(), checkfirst=True)

    op.create_table('categories',
                    sa.Column('id', sqlmodel.sql.sqltypes.GUID(),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('users',
                    sa.Column('id', sqlmodel.sql.sqltypes.GUID(),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=50), nullable=True),
                    sa.Column('last_name', sa.String(
                        length=50), nullable=True),
                    sa.Column('email', sa.String(length=255), nullable=True),
                    sa.Column('password', sa.String(
                        length=255), nullable=True),
                    sa.Column('phone_no', sa.String(length=24), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('is_admin', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('events',
                    sa.Column('id', sqlmodel.sql.sqltypes.GUID(),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('categories_id', sa.Uuid(), nullable=True),
                    sa.Column('description', sa.String(
                        length=2048), nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('location', sa.String(
                        length=255), nullable=False),
                    sa.Column('image', sa.String(length=2048), nullable=False),
                    sa.Column('evt_type', EventTypeEnum, nullable=False),
                    sa.Column('hide_rsvp_list', sa.Boolean(), nullable=True),
                    sa.Column('owner_id', sa.Uuid(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['categories_id'], ['categories.id'], ),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('event_categories',
                    sa.Column('event_id', sa.Uuid(), nullable=False),
                    sa.Column('category_id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['categories.id'], ),
                    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
                    sa.PrimaryKeyConstraint('event_id', 'category_id')
                    )
    op.create_table('rsvps',
                    sa.Column('id', sqlmodel.sql.sqltypes.GUID(),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('is_attending', sa.Boolean(), nullable=False),
                    sa.Column('is_bringing_extra',
                              sa.Boolean(), nullable=False),
                    sa.Column('extra_persons', sa.ARRAY(
                        sa.String()), nullable=True),
                    sa.Column('event_id', sa.Uuid(), nullable=True),
                    sa.Column('user_id', sa.Uuid(), nullable=True),
                    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rsvps')
    op.drop_table('event_categories')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('categories')
    EventTypeEnum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
